site_name: My Dialy
theme:
  name: material
  language: ja
  logo: android.png
  favicon: android.png
  palette:
    scheme: slate
    primary: blue
    accent: orange
  features:
    - tabs
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
