name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.8'
      - name: Install mkdocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material pyyaml
      - name: Init MkDocs
        run: |
          mkdocs new .
          python .mkdocs/scripts/prepare_docs.py
      - name: Build MkDocs
        run: mkdocs build --verbose --clean --strict
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
